### ISSUE TITLE
eMASS TRExport Format Report Lacks Data in the "AP Acronym" Column

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#33]
eMASS TRExport Format Report Lacks Data in the "AP Acronym" Column (Coulmn C).  This would be the AC-1(2).1 level label (note the dot one, dot two, etc. denoting the individual CCI this represents).  While a unique index is available in the CCI column, this AP Acronym format is also useful for searching and performing VLOOKUPs in the spreadsheets.

**Comment by TheCleverEpithet** [comment]
Sorry.... I didn't realize how you felt about AP Acronym when I created this.... :-)

//AP Acronym is nonsense; ignore it

**Comment by squinky86** [comment]
Ha! That part of the code was written when I was trying to find a fully unclassified source of eMASS-specific assessment procedure identifiers. Back before the DoD switched to eMASS, we begrudgingly called it the "dot numbers" or "dot notation" because it's an artifact from eMASS' handling of DIACAP controls. They were replaced with CCI numbers, and we were told for 3 years that eMASS would be dropping the dot notation in favor of going with CCI numbers.

The problem is that they aren't standardized. There are a few that have changed several times since their inception: it's just a number eMASS used to use internally.

That having been said, if you import a TRExport, *some* of the APs can be imported from that. I'll leave this bug open, but I'd like to find a fully unclassified, public release source of them before implementing this.

**Comment by TheCleverEpithet** [comment]
I think this is an unclass download from the IASE site:

http://iasecontent.disa.mil/stigs/zip/u_cci_list.zip

But it appears to be incomplete as some CCIs in this list do not have a ZZ-0(0).X format mapping, although many do.  This may not be useful here, but wanted to mention it as a possible resource?

**Comment by squinky86** [comment]
It only contains dot format for 800-53rev1, and the numbers don't match what's in eMASS in several cases. Public information regarding the dot format died after rev1, and it's now maintained internally by the eMASS devs.

I have 2 specific scenarios from back when we relied on the dot notation as a unique identifier. When the numbers changed in eMASS, it caused a mess. Had we been using the CCI number (the standardized identifier), we would have been fine.

**Comment by TheCleverEpithet** [comment]
I agree that it can jack things up and that was a really old and incomplete reference I linked to...  

Could we modify this feature request and just remove the AP Acronym column?  The primary objective of this report/output is to get the Max CAT I/II/III Severity or high watermark for each individual CCI.  The AP acronym is present in the NETCOM spreadsheet, but so is the CCI number and we can key on just the CCI.  

If that makes this easier and/or more palatable, it would still get us the key information that we need for the RAW which is high watermark CAT severity per CCI.

**Comment by squinky86** [comment]
When I remove the column, it doesn't import directly into eMASS anymore. Leaving it blank allows the spreadsheet to go straight from STIGQter to eMASS. I haven't tested it with hiding the column.

**Comment by TheCleverEpithet** [comment]
This would be a completely separate report/output function from the TRExport / eMASS import.  The output requested by this feature would not interface with eMASS.  It would only be used with the NETCOM RAW Risk Calculator Workbook thing.

**Comment by TheCleverEpithet** [comment]
EDIT: Comment removed - I was lost and confused and commenting on the wrong bug...

**Comment by squinky86** [comment]
The AP Number is now imported when you import eMASS test results. Reports that display its information now include it when applicable.
