### ISSUE TITLE
[Feature] Prompt to Save When Clicking "Quit"? 

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#44]
Does the application auto-save the database you're working in and re-open where you left off when re-open the tool, or does the tool reopen the database you were working in from the last time you saved it?

Could the tool prompt the user to Save When Clicking "Quit"?

**Comment by squinky86** [comment]
Everything is auto-saved in either:
1. ./STIGQter.db (if it exists)
2. %APPDATA%\STIGQter\STIGQter.db (windows - it'll be in a hidden directory in $HOME on Linux)

I'm adding a feature so that if you did save to an external .stigqter file, it is checked when you close to make sure that you didn't want to save to it again.
