### ISSUE TITLE
Remapping Unmapped STIG Checks to "All CM-6" not working correctly

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#72]
Test Case Steps (with fresh DB build):

1. Imported all CCIs in STIGQter
2. Imported ******* into STIGQter (This STIG was chosen because none of the STIG checks have CCI mappings in the STIG).
3. Opened STIG Viewer (v2.9.1) and created a Checklist file with this same STIG
4. Marked all STIG Checks as "Open" and save the Checklist file.
5. Imported the newly created STIG Checklist into STIGQter
6. Checked the "Remap to All CM-6" checkbox. 
7. Imported a TRE eMASS Sheet that contains multiple CM-6 CCIs.  
8. Clicked "Remap CM-6" button (note the alert window that pops up still says it is mapping to only CCI-366).  
9. Clicked "Reports" Menu, and clicked "eMASS Test Results" and saved the resulting spreadsheet.

Results:

Upon opening the resulting eMASS Test Result spreadsheet, all the STIG checks were mapped only to CCI-000366 and not to any of the other CM-6 CCIs. 

Note: This was tested with v1.0.1 Nightly Build pulled down on 8 May 2020.

**Comment by TheCleverEpithet** [comment]
Notes on order of testing steps:

Order of Scenario 1 Steps: New DB, Import CCIs, Import STIG, Import CKL, import eMASS Sheet, Check Remap to All CM-6 Checkbox, Click Remap CM-6 button, go to reports menu and generate eMASS Test Results report. Doesn't Work - only puts test results on CCI-000366.

 Scenario 2 Steps: New DB, Import CCIs, Import eMASS Sheet, Check Remap to All CM-6 Checkbox, Click Remap CM-6 button, Import STIG, Import CKL, go to reports menu and generate eMASS Test Results report.  Works - puts test results on all CM-6 CCIs.

**Comment by squinky86** [comment]
The two scenarios above have slightly different use cases. The options may better be seen in describing the two locations of the processes in which a STIG gets mapped:

- When importing a STIG, the STIG Check only gets remapped to CM-6 when it is not already mapped to a valid CCI (regardless of categorization).
- When clicking the "Remap" button, you're saying that even if the STIGs mapped to CCIs that are not included in the TRExport sheet that's been imported should be remapped. IE: a STIG Check mapped against a CCI that's not in the system's baseline should be remapped to a CCI that is (or CCI-366 if no CM-6 CCIs are in the baseline).

Both of your scenarios are hitting the first option: importing a STIG that is not properly mapped.

In Scenario 1, a STIG is coming in, and it's not mapped to a CCI. STIGQter sees that the "Remap to All CM-6" checkbox is not checked, and it does its best by remapping to just CCI-366. When you get to the point of clicking the "Remap" button, the STIG Checks are already mapped to a correct CCI (CCI-366) and don't get remapped again.

In Scenario 2, you check the the checkbox before importing the STIG. The remapping occurs at the "Import STIG" step rather than the "Remap" button (which is definitely confusing) since this is an erroneously mapped STIG from DISA.

There are a few ways that I think can help avoid confusion:
1. Don't remap STIGs during import. This prevents STIGQter from being useful unless a TRExport sheet is imported, because the unmapped and incorrectly mapped STIG Checks will not show up in many reports. (IE: not a good option)
2. Create a dummy CCI (CCI-999999) that incorrectly mapped STIG Checks map against. When you click the "Remap" button, anything mapping to this CCI gets remapped to CM-6 or CCI-366. This is like the first option, but it provides no consistency with any other RMF applications.
3. Make the warning more apparent when a STIG is imported so that the user knows STIG Checks were remapped on STIG import. This keeps things working as-is, and it avoids some of the confusion with what the "Remap" button is intended to do.
4. When a STIG is remapped on import, mark it as being remapped. Remap it again if the "Remap" button is pressed.

What I worry about is that the remap feature was meant to make things work more consistently with NETCOM guidance, but now, NETCOM guidance is to go with the further inconsistencies of eMASS. Both of the options above just introduce more inconsistencies. DISA introduces inconsistencies by mapping to CCIs that don't exist, then eMASS tries to fix them by mapping to CM-6. STIGQter can duplicate this (keep the checkbox checked before importing STIGs). But then there're the cases where the STIG Checks map to CCIs that merely aren't in the baseline. eMASS wets the bed while STIGQter provides the "Remap" button to save them from the abyss.

I think fix #4 makes the most sense, even though it's going to take the longest amount of time to implement. For now, make sure that the checkbox is checked before importing any STIGs.

This will, however, introduce a new use case: suppose that someone imports a TRExport sheet at the LLL level and remaps the CCIs. Any STIG Checks mapped against a CCI that only appears in a higher categorization will get remapped to CM-6. Now suppose that the user comes back and recategorizes as HHH. What should STIGQter do? We'll have to keep up with the remapping history for each STIGCheck to handle these scenarios, which is getting terribly complex...

**Comment by squinky86** [comment]
Talked to @TheCleverEpithet - I think we agree that the fourth fix option makes the most sense.

**Comment by squinky86** [comment]
Should be fixed in the next nightly with option #4. Note that the database format was updated, so make sure to start with a clean DB.
