### ISSUE TITLE
[Feature Enhancement] Replace "Index Quarterly" with "Index Current STIGs" from public.cyber.mil

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#90]
The Quarterly Library zip from DISA is notoriously incomplete and does not include all of the unclassified published STIGs from public.cyber.mil (not talking about the FOUO STIG zip vs the Unclass STIG Zip deltas).  

Would it be possible to change the way this button works from importing/indexing to quarterly library zip, to simply crawling the public.cyber.mil downloadable STIG zips at that point in time and importing all that are available? This way all the available STIGs would be loaded up to date as of the time the user clicked the button, vice the incomplete most recent quarterly library zip?

https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/<fileame>_STIG.zip

If this was the approach, the benchmark zips may be mixed in that same path, so that may or may not be a concern for sucking them in on top of the full STIGs. 

Not sure if this is feasible or worth the effort.  Just an idea for consideration. Not an immediate need.

**Comment by squinky86** [comment]
Ok, instead of a crawler, I did it like this:
https://www.stigqter.com/stig.php now points to the latest STIG non-FOUO compilation. When it moves/changes, it's a lot easier to just update that .php file than update a crawler and/or issue a new STIGQter version. It'll still be reactive, but hopefully not as problematic.
